### ISSUE TITLE
对于注释颜色的小建议

### ISSUE THREAD

**Issue by naivexcited** [lybest/feel-good#1]
您好，这个主题非常漂亮，我很喜欢，用了有一段时间了。唯一的不足是注释comment的颜色和背景颜色的区分度太低了，看起来很费劲，尤其是当光标所在的那一行被高亮的时候，几乎不可读。既然是深色背景，那建议可以把注释的颜色稍微提亮一些，增加一些辨识度。

**Comment by lybest** [comment]
好的 明天重新发布下
